/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Scanner;

public class App {
    public void first(Path path) {

        Scanner Books;
        try {
            Books = new Scanner(new File("src/main/resources/gates.js"));
        } catch (FileNotFoundException e) {
//            e.printStackTrace();
            System.out.println("We couldn't find that book, could you get a better filepath?");
            return;

        }
    }
}
